// Generate comprehensive synthetic data for demo purposes

const getRandomDate = (start, end) => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

const getDateDaysAgo = (days) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

export const generateSyntheticData = () => {
  // Farms
  const farms = [
    {
      id: '1',
      name: 'Green Valley Farm',
      location: 'Karnataka, India',
      totalArea: 25.5,
      unit: 'acres',
      latitude: 12.9716,
      longitude: 77.5946,
      established: '2018-03-15',
      ownerName: 'Frank Luong',
      createdAt: getDateDaysAgo(365),
    },
  ];

  // Plots
  const plots = [
    {
      id: '1',
      farmId: '1',
      name: 'North Field',
      area: 8.5,
      unit: 'acres',
      cropType: 'Tomato',
      variety: 'Roma Tomato',
      plantingDate: getDateDaysAgo(90),
      expectedHarvestDate: getDateDaysAgo(-30),
      soilType: 'Loamy',
      irrigationType: 'Drip Irrigation',
      status: 'Active',
      createdAt: getDateDaysAgo(365),
    },
    {
      id: '2',
      farmId: '1',
      name: 'South Field',
      area: 10.0,
      unit: 'acres',
      cropType: 'Rice',
      variety: 'Basmati',
      plantingDate: getDateDaysAgo(120),
      expectedHarvestDate: getDateDaysAgo(-10),
      soilType: 'Clay Loam',
      irrigationType: 'Flood Irrigation',
      status: 'Active',
      createdAt: getDateDaysAgo(365),
    },
    {
      id: '3',
      farmId: '1',
      name: 'East Field',
      area: 7.0,
      unit: 'acres',
      cropType: 'Wheat',
      variety: 'Durum Wheat',
      plantingDate: getDateDaysAgo(60),
      expectedHarvestDate: getDateDaysAgo(-60),
      soilType: 'Sandy Loam',
      irrigationType: 'Sprinkler',
      status: 'Active',
      createdAt: getDateDaysAgo(365),
    },
  ];

  // Activities
  const activities = [
    // Planting Activities
    {
      id: '1',
      farmId: '1',
      plotId: '1',
      type: 'Planting',
      cropType: 'Tomato',
      date: getDateDaysAgo(90),
      description: 'Planted Roma tomato seedlings',
      quantity: 5000,
      quantityUnit: 'seedlings',
      laborHours: 24,
      laborCost: 3600,
      notes: 'Spacing: 2ft x 3ft. Weather was favorable.',
      createdAt: getDateDaysAgo(90),
    },
    {
      id: '2',
      farmId: '1',
      plotId: '2',
      type: 'Planting',
      cropType: 'Rice',
      date: getDateDaysAgo(120),
      description: 'Transplanted rice seedlings',
      quantity: 8,
      quantityUnit: 'acres',
      laborHours: 40,
      laborCost: 6000,
      notes: 'Monsoon planting season',
      createdAt: getDateDaysAgo(120),
    },
    // Irrigation Activities
    {
      id: '3',
      farmId: '1',
      plotId: '1',
      type: 'Irrigation',
      cropType: 'Tomato',
      date: getDateDaysAgo(5),
      description: 'Drip irrigation - 4 hours',
      waterUsage: 2500,
      waterUnit: 'gallons',
      laborHours: 2,
      laborCost: 300,
      electricityCost: 450,
      notes: 'Regular watering schedule',
      createdAt: getDateDaysAgo(5),
    },
    {
      id: '4',
      farmId: '1',
      plotId: '2',
      type: 'Irrigation',
      cropType: 'Rice',
      date: getDateDaysAgo(3),
      description: 'Flood irrigation',
      waterUsage: 8000,
      waterUnit: 'gallons',
      laborHours: 6,
      laborCost: 900,
      notes: 'Maintained 2-3 inch water level',
      createdAt: getDateDaysAgo(3),
    },
    // Fertilization Activities
    {
      id: '5',
      farmId: '1',
      plotId: '1',
      type: 'Fertilization',
      cropType: 'Tomato',
      date: getDateDaysAgo(45),
      description: 'NPK fertilizer application',
      fertilizerType: 'NPK 19-19-19',
      quantity: 120,
      quantityUnit: 'kg',
      cost: 4500,
      applicationMethod: 'Fertigation',
      laborHours: 4,
      laborCost: 600,
      notes: 'Pre-flowering fertilization',
      createdAt: getDateDaysAgo(45),
    },
    {
      id: '6',
      farmId: '1',
      plotId: '2',
      type: 'Fertilization',
      cropType: 'Rice',
      date: getDateDaysAgo(60),
      description: 'Urea application - tillering stage',
      fertilizerType: 'Urea 46-0-0',
      quantity: 200,
      quantityUnit: 'kg',
      cost: 3000,
      applicationMethod: 'Broadcasting',
      laborHours: 8,
      laborCost: 1200,
      notes: 'Applied during tillering stage',
      createdAt: getDateDaysAgo(60),
    },
    {
      id: '7',
      farmId: '1',
      plotId: '3',
      type: 'Fertilization',
      cropType: 'Wheat',
      date: getDateDaysAgo(40),
      description: 'DAP application',
      fertilizerType: 'DAP 18-46-0',
      quantity: 150,
      quantityUnit: 'kg',
      cost: 5250,
      applicationMethod: 'Broadcasting',
      laborHours: 5,
      laborCost: 750,
      notes: 'Crown root initiation stage',
      createdAt: getDateDaysAgo(40),
    },
    // Pest Control Activities
    {
      id: '8',
      farmId: '1',
      plotId: '1',
      type: 'Pest Control',
      cropType: 'Tomato',
      date: getDateDaysAgo(30),
      description: 'Aphid control spray',
      pesticideType: 'Imidacloprid 17.8% SL',
      quantity: 2.5,
      quantityUnit: 'liters',
      cost: 2800,
      applicationMethod: 'Foliar spray',
      targetPest: 'Aphids',
      phi: 7,
      laborHours: 3,
      laborCost: 450,
      notes: 'Early morning application, no wind',
      createdAt: getDateDaysAgo(30),
    },
    {
      id: '9',
      farmId: '1',
      plotId: '2',
      type: 'Pest Control',
      cropType: 'Rice',
      date: getDateDaysAgo(50),
      description: 'Brown planthopper control',
      pesticideType: 'Thiamethoxam 25% WG',
      quantity: 1.5,
      quantityUnit: 'kg',
      cost: 3200,
      applicationMethod: 'Foliar spray',
      targetPest: 'Brown Planthopper',
      phi: 14,
      laborHours: 6,
      laborCost: 900,
      notes: 'Covered entire field uniformly',
      createdAt: getDateDaysAgo(50),
    },
    // Weeding Activities
    {
      id: '10',
      farmId: '1',
      plotId: '1',
      type: 'Weeding',
      cropType: 'Tomato',
      date: getDateDaysAgo(20),
      description: 'Manual weeding around plants',
      laborHours: 16,
      laborCost: 2400,
      notes: 'Removed broadleaf weeds',
      createdAt: getDateDaysAgo(20),
    },
    {
      id: '11',
      farmId: '1',
      plotId: '3',
      type: 'Weeding',
      cropType: 'Wheat',
      date: getDateDaysAgo(35),
      description: 'Herbicide application',
      herbicideType: '2,4-D Amine',
      quantity: 3,
      quantityUnit: 'liters',
      cost: 1800,
      applicationMethod: 'Spray',
      laborHours: 4,
      laborCost: 600,
      notes: 'Selective herbicide for broadleaf weeds',
      createdAt: getDateDaysAgo(35),
    },
    // Pruning/Maintenance
    {
      id: '12',
      farmId: '1',
      plotId: '1',
      type: 'Maintenance',
      cropType: 'Tomato',
      date: getDateDaysAgo(15),
      description: 'Pruning and staking',
      laborHours: 20,
      laborCost: 3000,
      materialCost: 2500,
      notes: 'Removed suckers, installed bamboo stakes',
      createdAt: getDateDaysAgo(15),
    },
    // Recent Activities
    {
      id: '13',
      farmId: '1',
      plotId: '1',
      type: 'Monitoring',
      cropType: 'Tomato',
      date: getDateDaysAgo(2),
      description: 'Crop health inspection',
      laborHours: 2,
      laborCost: 300,
      notes: 'Plants healthy, flowering stage. Some minor whitefly presence noted.',
      createdAt: getDateDaysAgo(2),
    },
    {
      id: '14',
      farmId: '1',
      plotId: '2',
      type: 'Irrigation',
      cropType: 'Rice',
      date: getDateDaysAgo(1),
      description: 'Water level maintenance',
      waterUsage: 5000,
      waterUnit: 'gallons',
      laborHours: 3,
      laborCost: 450,
      notes: 'Adjusted water level to 4 inches',
      createdAt: getDateDaysAgo(1),
    },
  ];

  // Harvests
  const harvests = [
    {
      id: '1',
      farmId: '1',
      plotId: '1',
      cropType: 'Tomato',
      date: getDateDaysAgo(10),
      quantity: 450,
      unit: 'kg',
      grade: 'A',
      laborHours: 8,
      laborCost: 1200,
      notes: 'First harvest. Good quality fruits.',
      createdAt: getDateDaysAgo(10),
    },
    {
      id: '2',
      farmId: '1',
      plotId: '1',
      cropType: 'Tomato',
      date: getDateDaysAgo(7),
      quantity: 520,
      unit: 'kg',
      grade: 'A',
      laborHours: 9,
      laborCost: 1350,
      notes: 'Peak production period',
      createdAt: getDateDaysAgo(7),
    },
    {
      id: '3',
      farmId: '1',
      plotId: '1',
      cropType: 'Tomato',
      date: getDateDaysAgo(4),
      quantity: 480,
      unit: 'kg',
      grade: 'A',
      laborHours: 8,
      laborCost: 1200,
      notes: 'Excellent quality maintained',
      createdAt: getDateDaysAgo(4),
    },
    {
      id: '4',
      farmId: '1',
      plotId: '1',
      cropType: 'Tomato',
      date: getDateDaysAgo(1),
      quantity: 390,
      unit: 'kg',
      grade: 'A',
      laborHours: 7,
      laborCost: 1050,
      notes: 'Latest harvest',
      createdAt: getDateDaysAgo(1),
    },
    {
      id: '5',
      farmId: '1',
      plotId: '2',
      cropType: 'Rice',
      date: getDateDaysAgo(25),
      quantity: 2800,
      unit: 'kg',
      grade: 'Premium',
      laborHours: 48,
      laborCost: 7200,
      processingCost: 5600,
      notes: 'Full harvest. Moisture content 14%. Stored in proper conditions.',
      createdAt: getDateDaysAgo(25),
    },
  ];

  // Transactions - Income
  const transactions = [
    // Income from Tomato sales
    {
      id: '1',
      farmId: '1',
      type: 'Income',
      category: 'Crop Sales',
      amount: 18000,
      currency: 'INR',
      date: getDateDaysAgo(10),
      description: 'Tomato sale - 450 kg @ Rs.40/kg',
      buyer: 'Local Wholesale Market',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Received',
      relatedTo: 'Harvest',
      relatedId: '1',
      notes: 'Grade A tomatoes',
      createdAt: getDateDaysAgo(10),
    },
    {
      id: '2',
      farmId: '1',
      type: 'Income',
      category: 'Crop Sales',
      amount: 20800,
      currency: 'INR',
      date: getDateDaysAgo(7),
      description: 'Tomato sale - 520 kg @ Rs.40/kg',
      buyer: 'Local Wholesale Market',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Received',
      relatedTo: 'Harvest',
      relatedId: '2',
      createdAt: getDateDaysAgo(7),
    },
    {
      id: '3',
      farmId: '1',
      type: 'Income',
      category: 'Crop Sales',
      amount: 19200,
      currency: 'INR',
      date: getDateDaysAgo(4),
      description: 'Tomato sale - 480 kg @ Rs.40/kg',
      buyer: 'Local Wholesale Market',
      paymentMethod: 'Cash',
      paymentStatus: 'Received',
      relatedTo: 'Harvest',
      relatedId: '3',
      createdAt: getDateDaysAgo(4),
    },
    {
      id: '4',
      farmId: '1',
      type: 'Income',
      category: 'Crop Sales',
      amount: 140000,
      currency: 'INR',
      date: getDateDaysAgo(24),
      description: 'Rice sale - 2800 kg @ Rs.50/kg',
      buyer: 'Rice Mill',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Received',
      relatedTo: 'Harvest',
      relatedId: '5',
      notes: 'Premium Basmati rice',
      createdAt: getDateDaysAgo(24),
    },
    // Expenses - Inputs
    {
      id: '5',
      farmId: '1',
      type: 'Expense',
      category: 'Seeds/Seedlings',
      amount: 12500,
      currency: 'INR',
      date: getDateDaysAgo(95),
      description: 'Roma tomato seedlings - 5000 units',
      supplier: 'Green Nursery',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: 'High-quality certified seedlings',
      createdAt: getDateDaysAgo(95),
    },
    {
      id: '6',
      farmId: '1',
      type: 'Expense',
      category: 'Seeds/Seedlings',
      amount: 8000,
      currency: 'INR',
      date: getDateDaysAgo(125),
      description: 'Basmati rice seeds - 80 kg',
      supplier: 'Seed Corporation',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      createdAt: getDateDaysAgo(125),
    },
    {
      id: '7',
      farmId: '1',
      type: 'Expense',
      category: 'Fertilizer',
      amount: 4500,
      currency: 'INR',
      date: getDateDaysAgo(45),
      description: 'NPK 19-19-19 - 120 kg',
      supplier: 'Agro Supply Store',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '5',
      createdAt: getDateDaysAgo(45),
    },
    {
      id: '8',
      farmId: '1',
      type: 'Expense',
      category: 'Fertilizer',
      amount: 3000,
      currency: 'INR',
      date: getDateDaysAgo(60),
      description: 'Urea 46-0-0 - 200 kg',
      supplier: 'Cooperative Society',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '6',
      createdAt: getDateDaysAgo(60),
    },
    {
      id: '9',
      farmId: '1',
      type: 'Expense',
      category: 'Fertilizer',
      amount: 5250,
      currency: 'INR',
      date: getDateDaysAgo(40),
      description: 'DAP 18-46-0 - 150 kg',
      supplier: 'Agro Supply Store',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '7',
      createdAt: getDateDaysAgo(40),
    },
    {
      id: '10',
      farmId: '1',
      type: 'Expense',
      category: 'Pesticides',
      amount: 2800,
      currency: 'INR',
      date: getDateDaysAgo(30),
      description: 'Imidacloprid 17.8% SL - 2.5 L',
      supplier: 'Pesticide Dealer',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '8',
      createdAt: getDateDaysAgo(30),
    },
    {
      id: '11',
      farmId: '1',
      type: 'Expense',
      category: 'Pesticides',
      amount: 3200,
      currency: 'INR',
      date: getDateDaysAgo(50),
      description: 'Thiamethoxam 25% WG - 1.5 kg',
      supplier: 'Pesticide Dealer',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '9',
      createdAt: getDateDaysAgo(50),
    },
    {
      id: '12',
      farmId: '1',
      type: 'Expense',
      category: 'Herbicides',
      amount: 1800,
      currency: 'INR',
      date: getDateDaysAgo(35),
      description: '2,4-D Amine - 3 L',
      supplier: 'Agro Supply Store',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '11',
      createdAt: getDateDaysAgo(35),
    },
    // Labor Expenses
    {
      id: '13',
      farmId: '1',
      type: 'Expense',
      category: 'Labor',
      amount: 3600,
      currency: 'INR',
      date: getDateDaysAgo(90),
      description: 'Planting labor - 24 hours',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '1',
      createdAt: getDateDaysAgo(90),
    },
    {
      id: '14',
      farmId: '1',
      type: 'Expense',
      category: 'Labor',
      amount: 6000,
      currency: 'INR',
      date: getDateDaysAgo(120),
      description: 'Rice transplanting labor - 40 hours',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '2',
      createdAt: getDateDaysAgo(120),
    },
    {
      id: '15',
      farmId: '1',
      type: 'Expense',
      category: 'Labor',
      amount: 3000,
      currency: 'INR',
      date: getDateDaysAgo(15),
      description: 'Pruning and staking - 20 hours',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '12',
      createdAt: getDateDaysAgo(15),
    },
    {
      id: '16',
      farmId: '1',
      type: 'Expense',
      category: 'Labor',
      amount: 7200,
      currency: 'INR',
      date: getDateDaysAgo(25),
      description: 'Harvest labor - 48 hours',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      relatedTo: 'Harvest',
      relatedId: '5',
      createdAt: getDateDaysAgo(25),
    },
    // Equipment & Maintenance
    {
      id: '17',
      farmId: '1',
      type: 'Expense',
      category: 'Equipment',
      amount: 2500,
      currency: 'INR',
      date: getDateDaysAgo(15),
      description: 'Bamboo stakes and ties for tomatoes',
      supplier: 'Local Market',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      relatedTo: 'Activity',
      relatedId: '12',
      createdAt: getDateDaysAgo(15),
    },
    {
      id: '18',
      farmId: '1',
      type: 'Expense',
      category: 'Equipment Maintenance',
      amount: 3500,
      currency: 'INR',
      date: getDateDaysAgo(55),
      description: 'Sprayer pump repair',
      supplier: 'Equipment Service Center',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      createdAt: getDateDaysAgo(55),
    },
    // Utilities
    {
      id: '19',
      farmId: '1',
      type: 'Expense',
      category: 'Electricity',
      amount: 4200,
      currency: 'INR',
      date: getDateDaysAgo(32),
      description: 'Monthly electricity bill for irrigation',
      paymentMethod: 'Online',
      paymentStatus: 'Paid',
      notes: 'Irrigation pump usage',
      createdAt: getDateDaysAgo(32),
    },
    {
      id: '20',
      farmId: '1',
      type: 'Expense',
      category: 'Water',
      amount: 2500,
      currency: 'INR',
      date: getDateDaysAgo(32),
      description: 'Water charges - monthly',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      createdAt: getDateDaysAgo(32),
    },
    // Processing
    {
      id: '21',
      farmId: '1',
      type: 'Expense',
      category: 'Processing',
      amount: 5600,
      currency: 'INR',
      date: getDateDaysAgo(25),
      description: 'Rice milling and cleaning',
      supplier: 'Modern Rice Mill',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      relatedTo: 'Harvest',
      relatedId: '5',
      createdAt: getDateDaysAgo(25),
    },
    // Transportation
    {
      id: '22',
      farmId: '1',
      type: 'Expense',
      category: 'Transportation',
      amount: 1500,
      currency: 'INR',
      date: getDateDaysAgo(24),
      description: 'Transport to rice mill',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      createdAt: getDateDaysAgo(24),
    },
  ];

  // Tasks - Calendar/Upcoming
  const tasks = [
    {
      id: '1',
      farmId: '1',
      plotId: '1',
      title: 'Tomato harvest',
      description: 'Continue regular harvesting every 3-4 days',
      dueDate: getDateDaysAgo(-2),
      priority: 'High',
      status: 'Pending',
      type: 'Harvest',
      recurring: true,
      frequency: 'Every 3 days',
      createdAt: getDateDaysAgo(10),
    },
    {
      id: '2',
      farmId: '1',
      plotId: '1',
      title: 'Irrigation - Tomato field',
      description: 'Drip irrigation for 4 hours',
      dueDate: getDateDaysAgo(-1),
      priority: 'High',
      status: 'Pending',
      type: 'Irrigation',
      recurring: true,
      frequency: 'Every 2 days',
      createdAt: getDateDaysAgo(7),
    },
    {
      id: '3',
      farmId: '1',
      plotId: '2',
      title: 'Water level check - Rice',
      description: 'Maintain 2-3 inch water level',
      dueDate: getDateDaysAgo(-1),
      priority: 'Medium',
      status: 'Pending',
      type: 'Monitoring',
      recurring: true,
      frequency: 'Daily',
      createdAt: getDateDaysAgo(5),
    },
    {
      id: '4',
      farmId: '1',
      plotId: '1',
      title: 'Pest monitoring - Tomato',
      description: 'Check for whitefly and early blight',
      dueDate: getDateDaysAgo(-3),
      priority: 'Medium',
      status: 'Pending',
      type: 'Monitoring',
      recurring: true,
      frequency: 'Weekly',
      createdAt: getDateDaysAgo(2),
    },
    {
      id: '5',
      farmId: '1',
      plotId: '3',
      title: 'Wheat harvest preparation',
      description: 'Inspect crop maturity, prepare for harvest in 2 months',
      dueDate: getDateDaysAgo(-7),
      priority: 'Low',
      status: 'Pending',
      type: 'Planning',
      createdAt: getDateDaysAgo(1),
    },
    {
      id: '6',
      farmId: '1',
      plotId: '2',
      title: 'Rice fertilizer application',
      description: 'Potash application for grain filling stage',
      dueDate: getDateDaysAgo(-5),
      priority: 'High',
      status: 'Pending',
      type: 'Fertilization',
      notes: 'Apply 100 kg Muriate of Potash',
      createdAt: getDateDaysAgo(3),
    },
    {
      id: '7',
      farmId: '1',
      plotId: '1',
      title: 'Order fertilizer',
      description: 'Order NPK for next application',
      dueDate: getDateDaysAgo(-10),
      priority: 'Medium',
      status: 'Pending',
      type: 'Procurement',
      notes: '150 kg NPK 19-19-19',
      createdAt: getDateDaysAgo(5),
    },
    {
      id: '8',
      farmId: '1',
      plotId: null,
      title: 'Equipment maintenance',
      description: 'Service irrigation pump and sprayer',
      dueDate: getDateDaysAgo(-14),
      priority: 'Medium',
      status: 'Pending',
      type: 'Maintenance',
      createdAt: getDateDaysAgo(7),
    },
  ];

  return {
    farms,
    plots,
    activities,
    harvests,
    transactions,
    tasks,
  };
};
